<?php

/**
 * Implements hook_views_api().
 */
function nnels_views_custom_handlers_views_api() {
  return [
    'api' => 3,
  ];
}

/**
 * Implements hook_views_post_execute().
 */
function nnels_views_custom_handlers_views_post_execute(&$view) {

  // File Size Warning Field.
  if (isset($view->field['file_size_warning'])) {
    _nnels_views_custom_handlers_set_file_size_warning_field($view);
  }
}

/**
 * Set File Size Warning Field.
 * 
 * @param object $view
 */
function _nnels_views_custom_handlers_set_file_size_warning_field(&$view) {
  foreach ($view->result as $result) {
    if (isset($view->field['filesize']) && isset($result->{$view->field['filesize']->field_alias})) {

      // If the filesize is greater than 400MB, show the file size warning.
      if ((int) $result->{$view->field['filesize']->field_alias} > 419430400) {
        $alt = t('Filesize Warning');
        $title = t('This file&apos;s size is larger than average on NNELS. Expect a longer download time than usual, depending on your connection.');
        $message = t('Long download time');
        $result->file_size_warning = '<div class="file-size-warning" alt="' . $alt . '" title="' . $title . '">';
        $result->file_size_warning .= '<i class="fa fa-exclamation-triangle" aria-hidden="true"> ' . $message . '</i>';
        $result->file_size_warning .= '</div>';
      }
    }

    // The file size warning is dependant on the filesize field. If the file-
    // size field is not present, display some warning text so the admin can
    // fix it.
    else {
      $result->file_size_warning = "'File: Size' field is missing and is required!";
    }
  }
}
